"""Id name change

Revision ID: 7d976b1473a1
Revises: fd37680f1475
Create Date: 2025-10-21 01:20:28.398743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d976b1473a1'
down_revision: Union[str, Sequence[str], None] = 'fd37680f1475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discountrule', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('discountrule', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('discountrule_manager_id_fkey'), 'discountrule', type_='foreignkey')
    op.create_foreign_key(None, 'discountrule', 'users', ['user_id'], ['id'])
    op.drop_column('discountrule', 'discount_rule_id')
    op.drop_column('discountrule', 'manager_id')
    op.add_column('purchase', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('purchase', 'purchase_id')
    op.add_column('sale', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('sale', 'sale_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('sale_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('sale', 'id')
    op.add_column('purchase', sa.Column('purchase_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('purchase', 'id')
    op.add_column('discountrule', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('discountrule', sa.Column('discount_rule_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'discountrule', type_='foreignkey')
    op.create_foreign_key(op.f('discountrule_manager_id_fkey'), 'discountrule', 'users', ['manager_id'], ['id'])
    op.drop_column('discountrule', 'user_id')
    op.drop_column('discountrule', 'id')
    # ### end Alembic commands ###
